export const Dummydata = [

    {
        id : 1,
        admin : 'avdesh',
        url : 'https://images.pexels.com/photos/5076531/pexels-photo-5076531.jpeg?cs=srgb&dl=pexels-cottonbro-5076531.jpg&fm=jpg',
        tittle : '10 tips for relaxation',
        des : 'Create a blog post subtitle that summarizes your post in a few short, punchy sentences and entices your audience to continue reading....',
        view : 3,
        comment : 2,
        totalLike : 5,
    },
    {
        id : 2,
        admin : 'mukesh',
        url : 'https://images.pexels.com/photos/6045233/pexels-photo-6045233.jpeg?cs=srgb&dl=pexels-skylar-kang-6045233.jpg&fm=jpg',
        tittle : 'Why taking action creates success',
        des : 'Create a blog post subtitle that summarizes your post in a few short, punchy sentences and entices your audience to continue reading....',
        view : 3,
        comment : 2,
        totalLike : 5,
    },
    {
        id : 3 ,
        admin : 'bimlesh',
        url : 'https://images.pexels.com/photos/5668808/pexels-photo-5668808.jpeg?cs=srgb&dl=pexels-sora-shimazaki-5668808.jpg&fm=jpg',
        tittle : 'Getting a grasp on adventure',
        des : 'Create a blog post subtitle that summarizes your post in a few short, punchy sentences and entices your audience to continue reading....',
        view : 3,
        comment : 2,
        totalLike : 5,
    },
    {
        id : 4,
        admin : 'ranjay',
        url : 'https://cdn.pixabay.com/photo/2014/12/28/13/20/wordpress-581849_960_720.jpg',
        tittle : 'Time for a change',
        des : 'Create a blog post subtitle that summarizes your post in a few short, punchy sentences and entices your audience to continue reading....',
        view : 3,
        comment : 2,
        totalLike : 5,
    },{
        id : 5,
        admin : 'sunil',
        url : 'https://cdn.pixabay.com/photo/2016/04/04/14/12/monitor-1307227_960_720.jpg',
        tittle : '5 secrets to finding happiness',
        des : 'Create a blog post subtitle that summarizes your post in a few short, punchy sentences and entices your audience to continue reading.... ',
        view : 3,
        comment : 2,
        totalLike : 5,
    },
]